- hosts: all
  sudo: true
  tasks:
    - name: Check if process running
      action: chkprocess process=httpd
      register: process
      #become: yes

    - debug: msg="{{ process.msg }}"

    - name: Check if user exists
      action: chkuser username=ec2-user
      register: user
      become: yes

    - debug: msg="{{ user.msg }}"

    - name: Add a list of users
      user: name={{ item }} state=present
      with_items:
        - Anmol
        - Mahesh
        - ganesh

