- hosts: all
  sudo: true

  vars:
   - MyMessage: "Welcome to Ansible World"
   - DBMessage: "Hello to MongoDB"
   - packname: java

  tasks:
   - name: Install tomcat
     yum: 
      name: tomcat
      state: present       
   - name: Install index Page  
     template: src: index-tomcat.html.j2 dest: /usr/share/tomcat/webapps/index.html 
