---
- hosts: all  #group name from the inventory
  gather_facts: no
  become: yes

  vars:
    remote_dir: "/tmp"

  tasks:
    - name: get the list of all file names inside the directory
      shell: "(cd {{remote_dir}}; find . -maxdepth 1 -type f) | cut -d'/' -f2"
      register: files_to_rename
      changed_when: no

    - name: Print File Names
      debug: var=files_to_rename

    - name: Print File Names
      debug: var=files_to_rename.stdout_lines

    - name: rename files inside directory 
      shell: "mv {{remote_dir}}/{{item.1}} {{ remote_dir }}/{{item.1}}.zip"
      become: yes
      register: rename_files_zip
      with_indexed_items: "{{files_to_rename.stdout_lines}}"


