---
- hosts: all  #group name from the inventory
  #sudo: true
  
  vars:
    pack_name: nginx
    serv_name: nginx
    become: yes
  
  tasks:
    - name: Install vim
      yum: pkg={{ pack_name }} state=installed
    - name: Start {{ serv_name }}
      service: name={{ serv_name }} state=started
...
